name: course-svc
on: 
 push: 
  branches: 
   - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       name: Set up JDK 17

     - uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven

     - name: Build with Maven
       run: mvn -B package --file pom.xml

     - name: Update dependency graph
       uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
 docker:
      runs-on: ubuntu-latest
      steps:

      - name: Build course-admin-server
        run: |
          cd course-admin-server
          docker build . --file Dockerfile --tag course-admin-server:$(date +%s)

      - name: Build course-consumer-course
        run: |
          cd ..
          cd course-consumer-course
          docker build . --file Dockerfile --tag course-consumer-course:$(date +%s)

      - name: Build course-consumer-order
        run: |
          cd .. 
          cd course-consumer-order
          docker build . --file Dockerfile --tag course-consumer-order:$(date +%s)

      - name: Build course-consumer-order
        run: |
          cd ..
          cd course-login
          docker build . --file Dockerfile --tag course-login:$(date +%s)
      
