name: course-svc
on: 
 push: 
  branches: 
   - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       name: Set up JDK 17

     - uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
     - name: Build with Maven
       run: mvn -B package --file pom.xml

     - name: Build build
       run: |
         docker build . --file ./course-admin-server/Dockerfile --tag course-admin-server:$(date +%s)
     - name: Build course-consumer-course
       run: |
         docker build . --file ./course-consumer-course/Dockerfile --tag course-consumer-course:$(date +%s)
     - name: Build course-consumer-order
       run: |
         docker build . --file ./course-consumer-order/Dockerfile --tag course-consumer-order:$(date +%s)
     - name: Build course-consumer-order
       run: |
         docker build . --file ./course-consumer-order/Dockerfile --tag course-login:$(date +%s)
    
